// app/legal/page.tsx
// Purpose: the full legal terms for Javari Market Oracle - what this is, what it is not,
//   and the protections around it.
// Date: 2026-09-12
//
// NOT LEGAL ADVICE FROM THE AUTHOR: this page was drafted to cover the risks that apply
// to a published AI stock-prediction experiment (no advice, no warranty, limited
// liability, indemnity, third-party data, AI limitations, forward-looking statements).
// It has NOT been reviewed by a licensed attorney. Roy: have counsel review before any
// paid tier, any advertising, or any claim of accuracy is published.
//
// CR AudioViz AI, LLC · EIN 39-3646201
import Link from "next/link";
import { MarketNav } from "@/components/MarketNav";

export const dynamic = "force-dynamic";

export const metadata = {
  title: "Legal — Javari Market Oracle",
  description: "Terms of use, disclaimers and limitations for Javari Market Oracle.",
};

const UPDATED = "September 12, 2026";

function Section({ id, title, children }: { id: string; title: string; children: React.ReactNode }) {
  return (
    <section aria-labelledby={id} className="mt-8">
      <h2 id={id} className="text-lg font-semibold text-white">{title}</h2>
      <div className="mt-2 space-y-3 text-sm leading-relaxed text-gray-300">{children}</div>
    </section>
  );
}

export default function LegalPage() {
  return (
    <>
      <MarketNav current="/legal" />
      <main id="main" className="mx-auto max-w-3xl px-3 py-5 sm:px-4">
        <h1 className="text-2xl font-bold text-white sm:text-3xl">Legal terms and disclaimers</h1>
        <p className="mt-2 text-sm text-gray-400">Last updated {UPDATED}. These terms apply to Javari Market Oracle, operated by CR AudioViz AI, LLC (EIN 39-3646201), Fort Myers, Florida.</p>

        <div className="mt-5 rounded-xl border border-amber-500/30 bg-amber-500/10 p-4">
          <p className="text-sm font-semibold text-amber-100">Javari Market Oracle is a public experiment measuring how accurately AI models predict stock movements. It is not investment advice, and it must not be used to make investment decisions.</p>
        </div>

        <Section id="what-this-is" title="1. What this service is">
          <p>Each weekday, several named AI models are given the same research pack and each one publicly predicts a single stock. Those predictions are scored against real prices. The purpose is to measure and compare AI accuracy over time, and to show the reasoning behind each prediction.</p>
          <p>Predictions are produced by artificial intelligence from public information. They are opinions generated by software, not the conclusions of any person, analyst or firm.</p>
        </Section>

        <Section id="no-advice" title="2. No investment advice; no professional relationship">
          <p>Nothing on this site is investment, financial, tax, accounting or legal advice, a recommendation, an offer, or a solicitation to buy or sell any security or other instrument. No content here is personalized to anyone's financial situation, objectives or risk tolerance.</p>
          <p>CR AudioViz AI, LLC is not a registered investment adviser, broker-dealer, or financial planner, and is not registered with the U.S. Securities and Exchange Commission, FINRA, or any state securities regulator. Using this site creates no advisory, fiduciary, brokerage or other professional relationship. Consult a licensed financial professional before making any investment decision.</p>
        </Section>

        <Section id="no-money" title="3. No wagering, no money, no prizes">
          <p>This is a free service. No wagers are accepted, no money changes hands, no securities are bought or sold here, and no prizes are awarded. Any "leaderboard", "standing", "win" or "score" refers solely to prediction accuracy in this experiment.</p>
        </Section>

        <Section id="ai-limits" title="4. Limits of AI predictions">
          <p>These models calculate and express opinions, not certainties, and they can be confidently wrong. They may misread data, rely on incomplete or outdated information, repeat errors present in their sources, or produce reasoning that sounds persuasive but is mistaken. A stated confidence level is the model's own estimate and is not a probability, a guarantee, or a measure of reliability.</p>
          <p>A model's past record on this site does not predict its future accuracy, and no model's record should be read as skill in markets generally.</p>
        </Section>


        <Section id="suitability" title="5. No suitability assessment">
          <p>No assessment has been made of whether any security, prediction or strategy shown here is suitable for you. Suitability depends on your financial situation, objectives, time horizon, tax position and tolerance for loss, none of which this service knows or considers. It should not be assumed that any security identified here was, or will be, profitable.</p>
        </Section>

        <Section id="no-human-review" title="6. Generated by software, without human review">
          <p>Predictions, confidence levels, targets, stop levels and written reasoning are produced automatically by AI models on a schedule, with no human analyst reviewing them before publication. No person at CR AudioViz AI evaluates, endorses or agrees with any individual prediction.</p>
        </Section>

        <Section id="no-position" title="7. No positions, no compensation, no conflicts">
          <p>CR AudioViz AI, LLC does not trade the securities discussed here, does not hold positions in them for the purpose of this service, and receives no compensation of any kind from any issuer, promoter, underwriter or third party in exchange for a security appearing on this site or being predicted, mentioned or rated.</p>
          <p>We do not engage in investment banking, market making, asset management, brokerage or securities underwriting.</p>
        </Section>

        <Section id="past-performance" title="8. Hypothetical results, past performance and forward-looking statements">
          <p>Past performance is not indicative of future results. All predictions, targets, stop levels and projected returns are forward-looking statements that involve known and unknown risks. Actual results will differ, and may differ substantially.</p>
          <p><strong className="text-white">Every result on this site is hypothetical.</strong> No trade is ever placed. Returns are measured from a recorded price to a later recorded price and exclude commissions, bid-ask spread, slippage, the price impact of trading, financing costs, dividends and taxes. They are not the returns of any actual portfolio and could not have been obtained by any investor. See our <Link href="/legal/performance" className="inline-block py-2 text-sky-300 underline">performance disclosure</Link>.</p>
        </Section>

        <Section id="data" title="9. Market data and third-party sources">
          <p>Prices, company data, earnings dates, insider filings and news are obtained from third-party providers and public sources. That information may be delayed, incomplete, interrupted or inaccurate, and it belongs to its respective owners. We do not independently verify it and do not warrant it.</p>
          <p>Links to third-party sites and articles are provided for reference. We do not endorse, control or take responsibility for their content.</p>
        </Section>

        <Section id="no-warranty" title="10. No warranty">
          <p>The service is provided "as is" and "as available", without warranty of any kind, express or implied, including but not limited to warranties of merchantability, fitness for a particular purpose, accuracy, non-infringement, and uninterrupted or error-free operation. We do not warrant that any prediction, score, calculation or report is accurate, complete or current.</p>
        </Section>

        <Section id="liability" title="11. Limitation of liability">
          <p>To the fullest extent permitted by law, CR AudioViz AI, LLC and its owners, officers, employees, contractors and suppliers are not liable for any direct, indirect, incidental, consequential, special, exemplary or punitive damages, or for any loss of profits, revenue, data, capital, trading losses, or investment losses, arising from or related to your use of, or inability to use, this service — whether based in contract, tort, negligence, strict liability or otherwise, and even if advised of the possibility of such damages.</p>
          <p>Where liability cannot be excluded by law, our total aggregate liability arising from the service will not exceed one hundred U.S. dollars ($100).</p>
        </Section>

        <Section id="your-responsibility" title="12. Your responsibility">
          <p>You are solely responsible for your own investment decisions and their outcomes. You agree not to rely on anything here in making them. You agree to indemnify and hold harmless CR AudioViz AI, LLC from any claim, loss, liability or expense (including reasonable legal fees) arising from your use of the service or your breach of these terms.</p>
        </Section>

        <Section id="acceptable-use" title="13. Acceptable use">
          <p>You may not scrape, resell, redistribute or present this content as your own or as advice, use it to operate a wagering or advisory service, attempt to circumvent access controls or rate limits, or use the service unlawfully. We may change, suspend or discontinue any part of the service at any time without notice.</p>
        </Section>

        <Section id="ip" title="14. Intellectual property and names">
          <p>The site, its design, text and compiled results are © 2026 CR AudioViz AI, LLC. AI model and company names (for example OpenAI, Mistral AI, NVIDIA, Alibaba, Z.ai, Groq) are the trademarks of their owners and are used descriptively to identify which model made a prediction. Their owners do not sponsor, endorse or participate in this service. Market data provider names and marks belong to their owners and are used only to credit the source. Company names and ticker symbols identify the securities discussed and imply no affiliation or endorsement.</p>
        </Section>

        <Section id="privacy" title="15. Privacy and cookies">
          <p>Accounts are provided through the CR AudioViz AI platform. We collect only what is needed to operate the service and do not sell personal information. Published pages show model predictions and results; they do not publish your personal information.</p>\n          <p>We and our infrastructure providers use cookies and similar technology to keep you signed in and to keep the service running. Blocking them may stop parts of the site from working.</p>
        </Section>

        <Section id="eligibility" title="16. Eligibility and jurisdiction">
          <p>The service is intended for users aged 18 or over in the United States. It is not directed at, and may not be lawful in, jurisdictions where the publication of market commentary requires registration. You are responsible for complying with the laws that apply to you.</p>
        </Section>

        <Section id="governing-law" title="17. Governing law">
          <p>These terms are governed by the laws of the State of Florida, without regard to its conflict-of-laws rules. The exclusive venue for any dispute is the state or federal courts located in Lee County, Florida. If any provision is held unenforceable, the remainder stays in effect.</p>
        </Section>

        <Section id="changes" title="18. Changes">
          <p>We may update these terms. Continued use after an update means you accept the revised terms; the date at the top shows when they last changed.</p>
        </Section>

        <Section id="contact" title="19. Contact">
          <p>CR AudioViz AI, LLC · EIN 39-3646201 · Fort Myers, Florida · <a className="inline-block py-2 text-sky-300 underline" href="https://craudiovizai.com">craudiovizai.com</a></p>
        </Section>

        <p className="mt-10 text-sm"><Link href="/how-it-works" className="inline-flex min-h-[2.75rem] items-center text-sky-300 underline">How the contest works →</Link></p>
      </main>
      <footer className="mx-auto max-w-3xl px-4 pb-10 text-xs text-gray-500">
        <p>© 2026 CR AudioViz AI, LLC · EIN 39-3646201 · Fort Myers, Florida</p>
      </footer>
    </>
  );
}
