// app/page.tsx — javari-market (Market Oracle)
// Live data dashboard — real Yahoo Finance prices, real AI picks from Supabase
// Prices refresh every 60s. Picks auto-generated by cron at 9:35 AM ET weekdays.
// CR AudioViz AI · EIN 39-3646201 · May 2026
'use client'
import { useState, useEffect, useCallback } from 'react'
import { TrendingUp, TrendingDown, Bell, Brain, BarChart3, Search,
  Star, Activity, Zap, ArrowUp, ArrowDown, Target, Sparkles,
  RefreshCw, Clock, AlertCircle, ExternalLink } from 'lucide-react'

export default function MarketOraclePage() {
  const [tab, setTab] = useState('dashboard')
  const [quotes, setQuotes] = useState({})
  const [picks, setPicks] = useState([])
  // Load watchlist from localStorage on client, fall back to defaults
  const DEFAULT_WATCHLIST = ['AAPL','MSFT','NVDA','TSLA','GOOGL','AMZN','META','SPY','QQQ','BRK-B']
  const [watchlist, setWatchlist] = useState(DEFAULT_WATCHLIST)
  const [searchInput, setSearchInput] = useState('')
  const [loading, setLoading] = useState(true)
  const [quotesLoading, setQuotesLoading] = useState(false)
  const [lastUpdated, setLastUpdated] = useState(null)
  const [error, setError] = useState('')
  const [marketStatus, setMarketStatus] = useState('checking')

  const fetchQuotes = useCallback(async (symbols) => {
    if (!symbols || symbols.length === 0) return
    setQuotesLoading(true)
    try {
      const res = await fetch(`/api/live-quotes?symbols=${symbols.join(',')}`)
      const data = await res.json()
      if (data.quotes) {
        setQuotes(prev => ({ ...prev, ...data.quotes }))
        setLastUpdated(new Date())
        setError('')
        // Determine market status from first quote
        const first = Object.values(data.quotes)[0]
        if (first) setMarketStatus('open')
      }
    } catch (e) {
      setError('Live data unavailable — retrying...')
    }
    setQuotesLoading(false)
    setLoading(false)
  }, [])

  const fetchPicks = useCallback(async () => {
    try {
      const res = await fetch('/api/dashboard-data?category=stock&limit=10')
      const data = await res.json()
      if (Array.isArray(data)) setPicks(data.slice(0, 10))
      else if (data.picks) setPicks(data.picks.slice(0, 10))
    } catch { /* picks are optional */ }
  }, [])

  // Initial load — restore watchlist from localStorage
  useEffect(() => {
    try {
      const saved = localStorage.getItem('javari_market_watchlist')
      const wl = saved ? JSON.parse(saved) : DEFAULT_WATCHLIST
      setWatchlist(wl)
      fetchQuotes(wl)
    } catch { fetchQuotes(watchlist) }
    fetchPicks()
  }, [])

  // Refresh prices every 60 seconds
  useEffect(() => {
    const interval = setInterval(() => fetchQuotes(watchlist), 60000)
    return () => clearInterval(interval)
  }, [watchlist, fetchQuotes])

  function addToWatchlist(symbol) {
    const s = symbol.trim().toUpperCase()
    if (s && !watchlist.includes(s) && watchlist.length < 25) {
      const next = [...watchlist, s]
      setWatchlist(next)
      try { localStorage.setItem('javari_market_watchlist', JSON.stringify(next)) } catch {}
      fetchQuotes([s])
    }
    setSearchInput('')
  }

  function removeFromWatchlist(symbol) {
    const next = watchlist.filter(s => s !== symbol)
    setWatchlist(next)
    try { localStorage.setItem('javari_market_watchlist', JSON.stringify(next)) } catch {}
    setQuotes(prev => { const n = {...prev}; delete n[symbol]; return n })
  }

  const quoteList = watchlist.map(s => quotes[s]).filter(Boolean)
  const gainers = quoteList.filter(q => q.changePercent > 0).sort((a,b) => b.changePercent - a.changePercent).slice(0,5)
  const losers = quoteList.filter(q => q.changePercent < 0).sort((a,b) => a.changePercent - b.changePercent).slice(0,5)

  function fmt(n, decimals=2) {
    if (n == null) return '—'
    return n.toLocaleString('en-US', { minimumFractionDigits: decimals, maximumFractionDigits: decimals })
  }
  function fmtBig(n) {
    if (!n) return '—'
    if (n >= 1e12) return '$' + (n/1e12).toFixed(1) + 'T'
    if (n >= 1e9) return '$' + (n/1e9).toFixed(1) + 'B'
    if (n >= 1e6) return '$' + (n/1e6).toFixed(1) + 'M'
    return '$' + n.toLocaleString()
  }

  const S = {
    wrap: { background: '#030612', minHeight: '100vh', color: '#e2e8f0', fontFamily: 'system-ui, sans-serif' },
    nav: { position: 'fixed', top: 0, left: 0, right: 0, zIndex: 100, background: 'rgba(3,6,18,0.97)', backdropFilter: 'blur(12px)', borderBottom: '1px solid rgba(59,130,246,0.15)', height: 58, display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '0 24px' },
    card: { background: '#0a1020', border: '1px solid rgba(59,130,246,0.12)', borderRadius: 12, padding: '16px 20px' },
    label: { fontSize: 11, fontWeight: 700, color: '#334155', letterSpacing: '0.08em', textTransform: 'uppercase', marginBottom: 4 },
    tabBar: { display: 'flex', gap: 4, padding: '12px 24px', borderBottom: '1px solid rgba(59,130,246,0.08)', overflowX: 'auto' },
  }

  return (
    <div style={S.wrap}>
      {/* NAV */}
      <nav style={S.nav}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
          <TrendingUp size={20} color="#3b82f6" />
          <span style={{ fontWeight: 800, fontSize: 15, color: '#60a5fa' }}>Market Oracle</span>
          <span style={{ fontSize: 11, color: '#1e3a5f', padding: '2px 8px', background: 'rgba(59,130,246,0.1)', borderRadius: 4, border: '1px solid rgba(59,130,246,0.2)' }}>LIVE</span>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
          {lastUpdated && (
            <span style={{ fontSize: 11, color: '#334155' }}>
              <Clock size={11} style={{ display: 'inline', marginRight: 4 }} />
              {lastUpdated.toLocaleTimeString()}
            </span>
          )}
          <button onClick={() => fetchQuotes(watchlist)} disabled={quotesLoading}
            style={{ background: 'none', border: '1px solid rgba(59,130,246,0.2)', color: '#60a5fa', borderRadius: 6, padding: '5px 10px', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 4, fontSize: 12 }}>
            <RefreshCw size={12} style={{ animation: quotesLoading ? 'spin 1s linear infinite' : 'none' }} />
            Refresh
          </button>
          <a href="https://craudiovizai.com/auth/signup" style={{ background: 'linear-gradient(135deg,#2563eb,#1d4ed8)', color: 'white', borderRadius: 8, padding: '7px 16px', fontSize: 12, fontWeight: 700, textDecoration: 'none' }}>Sign In</a>
        </div>
      </nav>
      <div style={{ height: 58 }} />

      {/* ERROR BANNER */}
      {error && (
        <div style={{ background: 'rgba(239,68,68,0.1)', borderBottom: '1px solid rgba(239,68,68,0.2)', padding: '8px 24px', display: 'flex', alignItems: 'center', gap: 8 }}>
          <AlertCircle size={14} color="#f87171" />
          <span style={{ fontSize: 12, color: '#f87171' }}>{error}</span>
        </div>
      )}

      {/* TAB BAR */}
      <div style={S.tabBar}>
        {['dashboard','watchlist','ai-picks','alerts'].map(t => (
          <button key={t} onClick={() => setTab(t)}
            style={{ padding: '7px 16px', borderRadius: 8, border: 'none', cursor: 'pointer', fontSize: 13, fontWeight: 600, whiteSpace: 'nowrap',
              background: tab === t ? 'rgba(59,130,246,0.15)' : 'transparent',
              color: tab === t ? '#60a5fa' : '#475569' }}>
            {t.replace('-', ' ').replace(/^\w/, c => c.toUpperCase())}
          </button>
        ))}
      </div>

      {/* DASHBOARD TAB */}
      {tab === 'dashboard' && (
        <div style={{ padding: '20px 24px', maxWidth: 1200, margin: '0 auto' }}>
          {loading ? (
            <div style={{ textAlign: 'center', padding: '80px 0', color: '#334155' }}>
              <Activity size={32} style={{ marginBottom: 12, opacity: 0.4 }} />
              <p>Loading live market data...</p>
            </div>
          ) : (
            <>
              {/* MARKET MOVERS ROW */}
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16, marginBottom: 20 }}>
                {/* Top Gainers */}
                <div style={S.card}>
                  <div style={{ ...S.label, color: '#10b981', marginBottom: 12 }}>
                    <ArrowUp size={11} style={{ display: 'inline', marginRight: 4 }} />Top Gainers (Today)
                  </div>
                  {gainers.length === 0 ? (
                    <p style={{ color: '#334155', fontSize: 13 }}>Add stocks to watchlist to see movers</p>
                  ) : gainers.map(q => (
                    <div key={q.symbol} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '7px 0', borderBottom: '1px solid rgba(255,255,255,0.04)' }}>
                      <div>
                        <span style={{ fontWeight: 700, fontSize: 13, color: '#e2e8f0' }}>{q.symbol}</span>
                        <span style={{ fontSize: 11, color: '#475569', marginLeft: 6 }}>{q.name?.slice(0,20)}</span>
                      </div>
                      <div style={{ textAlign: 'right' }}>
                        <div style={{ fontWeight: 700, fontSize: 13 }}>${fmt(q.price)}</div>
                        <div style={{ fontSize: 11, color: '#10b981', fontWeight: 600 }}>+{fmt(q.changePercent)}%</div>
                      </div>
                    </div>
                  ))}
                </div>
                {/* Top Losers */}
                <div style={S.card}>
                  <div style={{ ...S.label, color: '#ef4444', marginBottom: 12 }}>
                    <ArrowDown size={11} style={{ display: 'inline', marginRight: 4 }} />Top Losers (Today)
                  </div>
                  {losers.length === 0 ? (
                    <p style={{ color: '#334155', fontSize: 13 }}>No losers yet today — market may be closed</p>
                  ) : losers.map(q => (
                    <div key={q.symbol} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '7px 0', borderBottom: '1px solid rgba(255,255,255,0.04)' }}>
                      <div>
                        <span style={{ fontWeight: 700, fontSize: 13, color: '#e2e8f0' }}>{q.symbol}</span>
                        <span style={{ fontSize: 11, color: '#475569', marginLeft: 6 }}>{q.name?.slice(0,20)}</span>
                      </div>
                      <div style={{ textAlign: 'right' }}>
                        <div style={{ fontWeight: 700, fontSize: 13 }}>${fmt(q.price)}</div>
                        <div style={{ fontSize: 11, color: '#ef4444', fontWeight: 600 }}>{fmt(q.changePercent)}%</div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* FULL QUOTE TABLE */}
              <div style={S.card}>
                <div style={{ ...S.label, marginBottom: 16 }}>Live Market Data · Refreshes every 60s</div>
                <div style={{ overflowX: 'auto' }}>
                  <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 13 }}>
                    <thead>
                      <tr style={{ color: '#334155', fontSize: 11 }}>
                        {['Symbol','Name','Price','Change','% Change','Day Range','52W High','52W Low','Mkt Cap','Volume'].map(h => (
                          <th key={h} style={{ padding: '6px 10px', textAlign: 'right', fontWeight: 600, letterSpacing: '0.05em', ...(h === 'Symbol' || h === 'Name' ? { textAlign: 'left' } : {}) }}>{h}</th>
                        ))}
                      </tr>
                    </thead>
                    <tbody>
                      {quoteList.map(q => (
                        <tr key={q.symbol} style={{ borderTop: '1px solid rgba(255,255,255,0.04)' }}>
                          <td style={{ padding: '10px', fontWeight: 700, color: '#60a5fa' }}>{q.symbol}</td>
                          <td style={{ padding: '10px', color: '#94a3b8', maxWidth: 160, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{q.name}</td>
                          <td style={{ padding: '10px', textAlign: 'right', fontWeight: 600 }}>${fmt(q.price)}</td>
                          <td style={{ padding: '10px', textAlign: 'right', color: q.change >= 0 ? '#10b981' : '#ef4444', fontWeight: 600 }}>
                            {q.change >= 0 ? '+' : ''}{fmt(q.change)}
                          </td>
                          <td style={{ padding: '10px', textAlign: 'right', color: q.changePercent >= 0 ? '#10b981' : '#ef4444', fontWeight: 700 }}>
                            {q.changePercent >= 0 ? '+' : ''}{fmt(q.changePercent)}%
                          </td>
                          <td style={{ padding: '10px', textAlign: 'right', color: '#475569', fontSize: 12 }}>
                            ${fmt(q.dayLow)} — ${fmt(q.dayHigh)}
                          </td>
                          <td style={{ padding: '10px', textAlign: 'right', color: '#475569', fontSize: 12 }}>${fmt(q.week52High)}</td>
                          <td style={{ padding: '10px', textAlign: 'right', color: '#475569', fontSize: 12 }}>${fmt(q.week52Low)}</td>
                          <td style={{ padding: '10px', textAlign: 'right', color: '#475569', fontSize: 12 }}>{fmtBig(q.marketCap)}</td>
                          <td style={{ padding: '10px', textAlign: 'right', color: '#475569', fontSize: 12 }}>
                            {q.volume ? (q.volume / 1e6).toFixed(1) + 'M' : '—'}
                          </td>
                        </tr>
                      ))}
                      {quoteList.length === 0 && (
                        <tr><td colSpan={10} style={{ padding: 40, textAlign: 'center', color: '#334155' }}>Loading quotes...</td></tr>
                      )}
                    </tbody>
                  </table>
                </div>
              </div>
            </>
          )}
        </div>
      )}

      {/* WATCHLIST TAB */}
      {tab === 'watchlist' && (
        <div style={{ padding: '20px 24px', maxWidth: 900, margin: '0 auto' }}>
          <div style={{ ...S.card, marginBottom: 16 }}>
            <div style={{ ...S.label, marginBottom: 12 }}>Add Symbol</div>
            <div style={{ display: 'flex', gap: 10 }}>
              <input value={searchInput} onChange={e => setSearchInput(e.target.value.toUpperCase())}
                onKeyDown={e => e.key === 'Enter' && addToWatchlist(searchInput)}
                placeholder="AAPL, TSLA, BTC-USD..."
                style={{ flex: 1, background: '#030612', border: '1px solid rgba(59,130,246,0.2)', borderRadius: 8, padding: '10px 14px', color: '#e2e8f0', fontSize: 13, outline: 'none' }} />
              <button onClick={() => addToWatchlist(searchInput)}
                style={{ background: 'linear-gradient(135deg,#2563eb,#1d4ed8)', color: 'white', border: 'none', borderRadius: 8, padding: '10px 20px', fontWeight: 700, cursor: 'pointer', fontSize: 13 }}>
                + Add
              </button>
            </div>
          </div>
          {watchlist.map(symbol => {
            const q = quotes[symbol]
            return (
              <div key={symbol} style={{ ...S.card, marginBottom: 8, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
                  <span style={{ fontWeight: 700, fontSize: 15, color: '#60a5fa', minWidth: 60 }}>{symbol}</span>
                  {q ? (
                    <>
                      <span style={{ fontWeight: 700, fontSize: 16 }}>${fmt(q.price)}</span>
                      <span style={{ fontSize: 13, fontWeight: 600, color: q.changePercent >= 0 ? '#10b981' : '#ef4444' }}>
                        {q.changePercent >= 0 ? '▲' : '▼'} {Math.abs(q.changePercent).toFixed(2)}%
                      </span>
                      <span style={{ fontSize: 12, color: '#334155' }}>{q.name?.slice(0,30)}</span>
                    </>
                  ) : (
                    <span style={{ color: '#334155', fontSize: 12 }}>Loading...</span>
                  )}
                </div>
                <button onClick={() => removeFromWatchlist(symbol)}
                  style={{ background: 'none', border: '1px solid rgba(239,68,68,0.2)', color: '#ef4444', borderRadius: 6, padding: '4px 10px', cursor: 'pointer', fontSize: 12 }}>
                  Remove
                </button>
              </div>
            )
          })}
        </div>
      )}

      {/* AI PICKS TAB */}
      {tab === 'ai-picks' && (
        <div style={{ padding: '20px 24px', maxWidth: 900, margin: '0 auto' }}>
          <div style={{ ...S.card, marginBottom: 16, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <div>
              <div style={{ fontWeight: 700, fontSize: 15, color: '#e2e8f0', marginBottom: 4 }}>AI Stock Picks</div>
              <div style={{ fontSize: 12, color: '#334155' }}>Auto-generated at 9:35 AM ET on market days · Powered by Javari AI + live Yahoo Finance data</div>
            </div>
            <button onClick={fetchPicks} style={{ background: 'rgba(59,130,246,0.1)', border: '1px solid rgba(59,130,246,0.2)', color: '#60a5fa', borderRadius: 8, padding: '8px 14px', cursor: 'pointer', fontSize: 12, fontWeight: 600, display: 'flex', alignItems: 'center', gap: 6 }}>
              <RefreshCw size={12} /> Reload
            </button>
          </div>
          {picks.length === 0 ? (
            <div style={{ ...S.card, textAlign: 'center', padding: '60px 24px' }}>
              <Brain size={32} style={{ marginBottom: 12, opacity: 0.3 }} />
              <p style={{ color: '#334155', fontSize: 14, marginBottom: 16 }}>No picks loaded yet. Auto-picks run at 9:35 AM ET on market days.</p>
              <button onClick={async () => {
                try {
                  setPicks([])
                  const r = await fetch('/api/cron/auto-picks')
                  const d = await r.json()
                  if (d.picks && d.picks.length > 0) setPicks(d.picks)
                  else fetchPicks()
                } catch { fetchPicks() }
              }} style={{ background: 'linear-gradient(135deg,#2563eb,#1d4ed8)', color: 'white', border: 'none', borderRadius: 10, padding: '12px 24px', fontSize: 14, fontWeight: 700, cursor: 'pointer', marginBottom: 12 }}>
                ⚡ Generate Live Picks Now
              </button>
              <p style={{ color: '#1e3a5f', fontSize: 12 }}>Uses live Yahoo Finance data + Javari AI — free</p>
            </div>
          ) : picks.map((pick, i) => {
            const currentQ = quotes[pick.symbol]
            return (
              <div key={i} style={{ ...S.card, marginBottom: 10 }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
                    <div>
                      <span style={{ fontWeight: 800, fontSize: 16, color: '#60a5fa' }}>{pick.symbol || pick.ticker}</span>
                      <span style={{ marginLeft: 8, padding: '2px 8px', borderRadius: 4, fontSize: 11, fontWeight: 700,
                        background: (pick.action || pick.signal) === 'BUY' || (pick.action || pick.signal) === 'strong_buy' ? 'rgba(16,185,129,0.15)' : 'rgba(239,68,68,0.15)',
                        color: (pick.action || pick.signal) === 'BUY' || (pick.action || pick.signal) === 'strong_buy' ? '#10b981' : '#ef4444' }}>
                        {(pick.action || pick.signal || 'HOLD').toUpperCase()}
                      </span>
                    </div>
                    {currentQ && (
                      <div>
                        <span style={{ fontWeight: 700, fontSize: 15 }}>${fmt(currentQ.price)}</span>
                        <span style={{ marginLeft: 6, fontSize: 12, color: currentQ.changePercent >= 0 ? '#10b981' : '#ef4444' }}>
                          {currentQ.changePercent >= 0 ? '+' : ''}{fmt(currentQ.changePercent)}%
                        </span>
                      </div>
                    )}
                  </div>
                  <div style={{ textAlign: 'right' }}>
                    <div style={{ fontSize: 11, color: '#334155' }}>Confidence</div>
                    <div style={{ fontWeight: 700, color: '#60a5fa' }}>{pick.confidence || pick.score || 0}%</div>
                  </div>
                </div>
                {(pick.thesis || pick.reason) && (
                  <p style={{ marginTop: 10, fontSize: 13, color: '#64748b', lineHeight: 1.6, borderTop: '1px solid rgba(255,255,255,0.04)', paddingTop: 10 }}>
                    {pick.thesis || pick.reason}
                  </p>
                )}
                {pick.target_price && (
                  <div style={{ display: 'flex', gap: 16, marginTop: 8 }}>
                    <span style={{ fontSize: 11, color: '#334155' }}>Target: <strong style={{ color: '#10b981' }}>${fmt(pick.target_price)}</strong></span>
                    {pick.stop_loss && <span style={{ fontSize: 11, color: '#334155' }}>Stop: <strong style={{ color: '#ef4444' }}>${fmt(pick.stop_loss)}</strong></span>}
                    {pick.risk_level && <span style={{ fontSize: 11, color: '#334155' }}>Risk: <strong>{pick.risk_level}</strong></span>}
                  </div>
                )}
              </div>
            )
          })}
        </div>
      )}

      {/* ALERTS TAB */}
      {tab === 'alerts' && (
        <div style={{ padding: '20px 24px', maxWidth: 700, margin: '0 auto' }}>
          <div style={{ ...S.card, textAlign: 'center', padding: '60px 24px' }}>
            <Bell size={32} style={{ marginBottom: 12, opacity: 0.3 }} />
            <h3 style={{ color: '#e2e8f0', marginBottom: 8 }}>Price Alerts</h3>
            <p style={{ color: '#334155', fontSize: 14 }}>Sign in to create price alerts that notify you when stocks hit your targets.</p>
            <a href="https://craudiovizai.com/auth/signup" style={{ display: 'inline-block', marginTop: 16, background: 'linear-gradient(135deg,#2563eb,#1d4ed8)', color: 'white', borderRadius: 8, padding: '10px 24px', textDecoration: 'none', fontWeight: 700 }}>Sign In Free</a>
          </div>
        </div>
      )}

      <footer style={{ background: '#010308', borderTop: '1px solid rgba(59,130,246,0.08)', padding: '20px 24px', textAlign: 'center', marginTop: 40 }}>
        <p style={{ color: '#0f2040', fontSize: 11 }}>© 2026 CR AudioViz AI, LLC · EIN 39-3646201 · Market data via Yahoo Finance · Not investment advice</p>
      </footer>
    </div>
  )
}
