// app/api/ai-picks/generate/route.ts
// Purpose: reads the contest's real picks. Kept at this path because three pages call it.
// Date: 2026-09-11 (rewritten)
//
// What this used to be: a second, parallel pick system. POST called OpenAI/Anthropic/
// Google directly and wrote to `market_oracle_picks`; GET read that table back. It last
// produced anything in December 2025 and left 62 picks permanently unsettled, because
// nothing ever scored them. The live contest writes to `stock_picks` through Javari
// (lib/market/battle.ts), so this table was a dead end that still accepted new writes.
//
// POST is now gone: picks are made by the scheduled battle, never on demand from a
// browser. GET serves the real picks so the pages that call it keep working.
//
// CR AudioViz AI, LLC · EIN 39-3646201
import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import { secretKey, supabaseUrl } from "@craudioviz/platform-sdk";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

export async function POST(): Promise<NextResponse> {
  return NextResponse.json(
    {
      success: false,
      error: "Picks are generated by the daily battle, not on demand.",
      detail: "The AI models pick each weekday at 9:30 AM ET. See /how-it-works.",
    },
    { status: 410 },
  );
}

export async function GET(request: Request): Promise<NextResponse> {
  try {
    const { searchParams } = new URL(request.url);
    const symbol = searchParams.get("symbol");
    const slug = searchParams.get("ai");
    const limit = Math.min(Math.max(parseInt(searchParams.get("limit") ?? "20", 10) || 20, 1), 200);

    const url = supabaseUrl();
    const key = secretKey();
    if (!url || !key) return NextResponse.json({ success: false, error: "Database unavailable" }, { status: 503 });
    const db = createClient(url, key, { auth: { autoRefreshToken: false, persistSession: false } });

    const { data: models, error: mErr } = await db.from("ai_models").select("id, display_name, slug, color, provider, tagline").eq("is_active", true);
    if (mErr) throw new Error(mErr.message);
    const byId = new Map((models ?? []).map((m) => [m.id as string, m]));

    let q = db.from("stock_picks").select("*").not("javari_request_id", "is", null).order("pick_date", { ascending: false }).limit(limit);
    if (symbol) q = q.eq("symbol", symbol.toUpperCase());
    if (slug) {
      const model = (models ?? []).find((m) => m.slug === slug || m.id === slug);
      if (!model) return NextResponse.json({ success: true, picks: [], count: 0 });
      q = q.eq("ai_model_id", model.id);
    }
    const { data, error } = await q;
    if (error) throw new Error(error.message);

    const picks = (data ?? []).map((p) => {
      const m = byId.get(p.ai_model_id as string);
      return {
        id: p.id, symbol: p.symbol, company_name: p.company_name, direction: p.direction,
        confidence: p.confidence, entry_price: p.entry_price, current_price: p.current_price,
        target_price: p.target_price, stop_loss: p.stop_loss,
        thesis: p.reasoning_summary ?? p.reasoning, full_reasoning: p.reasoning,
        key_bullish_factors: p.key_factors ?? [], risks: p.risk_factors ?? [], sources: p.sources ?? [],
        status: p.status, result: p.result, return_percent: p.profit_loss_percent ?? p.price_change_percent,
        pick_date: p.pick_date, expires_at: p.expiry_date,
        ai_model: m?.slug ?? null, ai_model_name: m?.display_name ?? "Retired model",
        ai_model_color: m?.color ?? null, ai_provider: m?.provider ?? null,
      };
    });
    return NextResponse.json({ success: true, count: picks.length, picks });
  } catch (e) {
    console.error(JSON.stringify({ level: "error", msg: "market.ai_picks_get_failed", error: e instanceof Error ? e.message : String(e) }));
    return NextResponse.json({ success: false, error: "Could not load picks" }, { status: 500 });
  }
}
